### ISSUE TITLE
Performance Technologies, Inc. is now Sonus Networks, Inc.

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/CSHPublicSite#101]
One of our sponsors, Performance Technologies, Inc. has rebranded to Sonus Networks, Inc. and as a result the logo on our site is out of date and the link to their website is broken. This should be updated to reflect the current company's logo and website URL.

http://www.sonus.net/

![](https://media.licdn.com/media/p/5/005/049/235/21e3c2c.png)

**Comment by rswiernik** [comment]
Fixed in #104.
