### ISSUE TITLE
Nav Links Need To Be Absolutely Pathed

### ISSUE THREAD

**Issue by speakerbug** [ComputerScienceHouse/CSHPublicSite#107]
I've noticed this for a while and I just figured I'd make an issue for it so either I can fix it later or someone else can, but the 404 page on the site is unstyled.

![Screenshot of 404](https://cloud.githubusercontent.com/assets/8688530/13766986/e6ca3ca4-ea3c-11e5-9c83-ddf29b745a62.png)

**Comment by rswiernik** [comment]
Can you make sure that you have a non cached version? If still not fixed, what browser are you using?

**Comment by speakerbug** [comment]
It seems to be fixed.

**Comment by stevenmirabito** [comment]
This is not resolved. Assets are being relatively linked instead of absolutely, so going to any page beyond the top level (e.g. !(https://csh.rit.edu/asjdoias/adjhajsd)[]) will give you a page without any assets.

**Comment by speakerbug** [comment]
He's right. Sorry, I was tired so I just did a quick test and forgot to add an extra level which was the original problem.

**Comment by liam-middlebrook** [comment]
@brandonhudson why was this closed? It's still an isue for subdirectories as @stevenmirabito mentioned above?

http://www.csh.rit.edu/committee/section.html should 404 with a styled page

**Comment by GICodeWarrior** [comment]
This is still broken or broken again.  Example: http://www.csh.rit.edu/abc/123

**Comment by liam-middlebrook** [comment]
@brandonhudson why was https://github.com/ComputerScienceHouse/CSHPublicSite/commit/65382dea21e3fa985ebd6bf08b3f0db2fa4a9fa8 reverted? It was a known fix to this bug.

**Comment by brandonhudson** [comment]
@liam-middlebrook ahh, I remember why that needed to be reverted now - It doesn't work because your absolutely pathed to the include files, which does two things:
- When you go to build with PyBuilder, it breaks because it tries to access the templates from the absolute path of the system you're building on, not the project directory.
- The issue is that the resources were relatively pathed in the template files, and that fix wouldn't accomplish fixing the bug

Hence reverted.

**Comment by brandonhudson** [comment]
On another note, deploy will be coming shortly to test/fix this.

**Comment by liam-middlebrook** [comment]
It appears that the links are still relative so if you go to https://csh.rit.edu/erroneous/thiswill404 and try to click any of the navbar links, you'll still get the 404 page.
