### ISSUE TITLE
40th updates

### ISSUE THREAD

**Issue by ajgajg1134** [ComputerScienceHouse/CSHPublicSite#123]
I don't really care how these are displayed or organized just as long as they can be found.
It might be in order to create a FAQ page so we can add answers to questions as we get them

Add a section about child care:

> I've received a lot of questions recently regarding child care during the formal dinner portion of 40th. I'm sad to announce we will be unable to provide child care or recommend a location for use. If there are Rochester local parents who can recommend a babysitting service or local daycare for use to other parents I'd be happy to add links or phone numbers to the 40th website.
I apologize for getting this information to all of you late as I had been hoping we still may be able to locate something. This will be reflected in the post-mortem notes as something to figure out much earlier for 45th (and beyond) as well as to work with actual CSH alumni parents who have experience with places nearby.
If you have any concerns or questions feel free to email me at chairman@csh.rit.edu

add a section about parking:

> There is actually no ticketing or towing on campus (For non flagrant parking, so if you park in a handicapped spot or in a fire lane I make no promises) But C-Lot, B-Lot and even the "20-minute spots" outside NRH are all fair game both Saturday and Sunday (As well as Friday after 5pm) If you arrive before 5pm on Friday you can get a free 24 hour parking pass for dorm lots (aka C-Lot) See the RIT Parking website for more info on that.

Add a section saying if you have more questions you can email chairman@csh.rit.edu, check out "#40th" on slack, or post on the computer science house facebook group.

**Comment by ajgajg1134** [comment]
Also add a note on the polisseni center tours that they will begin at 2pm and meet at the polisseni center lobby

**Comment by brandonhudson** [comment]
https://github.com/ComputerScienceHouse/CSHPublicSite/pull/124 takes care of these.
