### ISSUE TITLE
40th Webpage is still being hosted

### ISSUE THREAD

**Issue by liam-middlebrook** [ComputerScienceHouse/CSHPublicSite#155]
https://csh.rit.edu/40th.html is still accessible, maybe the public site directory should be cleaned out and redeployed to remove other potential "stragglers".

**Comment by rswiernik** [comment]
Well, you know, HISTORY MAN.

I'll take a look at it later tonight :)

**Comment by devinmatte** [comment]
I think this issue is okay to be closed. The page look to no longer be accessible

**Comment by brandonhudson** [comment]
This is deployed.
