### ISSUE TITLE
Add FAQ Page

### ISSUE THREAD

**Issue by brandonhudson** [ComputerScienceHouse/CSHPublicSite#168]
We're facing more and more public criticism / skepticism about the processes and activities that we go through during the introductory process for incoming freshman students. To combat this, I propose that we become much more transparent about every step of the process, and break down what differentiates us from stereotypical fraternal organizations. With this, I'm hoping that we can better inform incoming students and parents about what exactly CSH is and what the process looks like for applying.

Initial topic ideas:

- Is CSH a Frat?
- What is the introductory process like?
- What is Freshman Project?
- What happens if I’m not accepted?

Please comment with thoughts / concerns - I'm going to leave this open for a couple weeks so we can have discussion.

**Comment by mbillow** [comment]
I think this could be super valuable in conveying what CSH is actually about and dispel some common misconceptions in our process(es). 

I think "What is the  intro process like?" might be a bit to vauge and lead to a huge block of text no one would want to read. I think it would be better if we broke it down into:
- How do I apply?
  - Mention the application and informal interview.
- What happens after I am accepted?
  - Packet overview, maybe mention learning quests.

Definitely like this idea though.
