### ISSUE TITLE
Remove the CSH Hacks section from the homepage

### ISSUE THREAD

**Issue by RamZallan** [ComputerScienceHouse/CSHPublicSite#236]
Since the hackathon was cancelled by COVID, we should remove the section from the homepage.

It was added w/ [this commit](https://github.com/ComputerScienceHouse/CSHPublicSite/pull/221/commits/91f11210b16627a31af2746206163f6a0cf63935), so someone can either just revert it, or if that causes too much weird git history since it was merged w/ other commits, just delete the section + make new commits to do so.

**Comment by mxmeinhold** [comment]
Fixed in #237
