### ISSUE TITLE
Update Constant Contact Logo

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/CSHPublicSite#247]

**Comment by klauscurde** [comment]
Attempt to fix with [PR 257](https://github.com/ComputerScienceHouse/CSHPublicSite/pull/257)

**Comment by mxmeinhold** [comment]
Looks like #257 got merged, along with #258. @klauscurde is this good to close?

**Comment by klauscurde** [comment]
Yup good to close.
