### ISSUE TITLE
Add Facebook to Alumni

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/CSHPublicSite#248]
@sauriol Signed a Facebook offer, and apparently we have older alumni there

**Comment by Dr-N0** [comment]
What changes does this entail?

**Comment by RamZallan** [comment]
@Dr-N0 Adding another line in the `about/alumni.html` listing Facebook, i.e.:
https://github.com/ComputerScienceHouse/CSHPublicSite/blob/682fc6b7c8bfc9c59db857473848c975c56c3dc9/about/alumni.html#L34
