### ISSUE TITLE
Page formatting

### ISSUE THREAD

**Issue by Dr-N0** [ComputerScienceHouse/CSHPublicSite#251]
I was thinking about changing up the navigation functionality a little bit.

Currently, we have a simple system, links on a top bar and you can click them which takes you to another page
<img width="858" alt="Screen Shot 2021-01-26 at 12 00 37 PM" src="https://user-images.githubusercontent.com/15280703/105877577-25fa6280-5fce-11eb-9390-a3be6ec4eaf9.png">
<img width="907" alt="Screen Shot 2021-01-26 at 12 00 48 PM" src="https://user-images.githubusercontent.com/15280703/105877606-2b57ad00-5fce-11eb-8ab2-14cf4628647a.png">

I would much rather we put all of the information of all of a section in one page (so this would be all of the membership tab together not everything together) and use the nav bar to hyper link between them. We would still differentiate the sections. So we'd have a large (revised) header for "Overview" and "New Members" and the current top header would, in this scenario, be "Members"

**Comment by Dr-N0** [comment]
Lmk what you all think

**Comment by Dr-N0** [comment]
Deleting the second point, after running through implementation of the the side nav bar, it'll be inconsistent since we use auto margins. First point will work though, will post mock up in a bit

**Comment by Dr-N0** [comment]
Currently the secondary header is just an h1 tag b/c mock, but that'll be heavily prettified. The links in the drop down will hyper link to the header's position on the page

<img width="1440" alt="Screen Shot 2021-01-26 at 1 20 09 PM" src="https://user-images.githubusercontent.com/15280703/105887137-5693c980-5fd9-11eb-9948-1f723d0bb705.png">
<img width="1440" alt="Screen Shot 2021-01-26 at 1 20 17 PM" src="https://user-images.githubusercontent.com/15280703/105887139-572c6000-5fd9-11eb-9302-fc787929a9b5.png">
<img width="1440" alt="Screen Shot 2021-01-26 at 1 20 23 PM" src="https://user-images.githubusercontent.com/15280703/105887141-572c6000-5fd9-11eb-8cf6-19fcfbc4d002.png">
<img width="766" alt="Screen Shot 2021-01-26 at 1 20 35 PM" src="https://user-images.githubusercontent.com/15280703/105887142-572c6000-5fd9-11eb-887d-7ea1e9570b56.png">

**Comment by RamZallan** [comment]
I don't especially love the UX of having everything membership-related (or everything about-related, etc) on one page. Kinda not sure what benefit we get from having all of the topics on one page vs a page for each tidbit, if anything it may be confusing. 

Also, our alumni, sponsor, and eboard pages are huge grids, would be a pain to be scrolling through.

@devinmatte @mxmeinhold any thoughts?

**Comment by devinmatte** [comment]
I think the whole "one page for everything" trend is dumb. I would rather things remain separate pages here and if we want, a footer for the page linking to the "next page"

**Comment by Dr-N0** [comment]
Gotcha, if that's the case then I'd rather as is then add an arrow system since it could confuse the flow a bit, and I'm not sure how it would fit with the current footer

**Comment by devinmatte** [comment]
Instead of an arrow flow maybe at the bottom of Overview a link to `Read about our process for new Members` at the bottom, so develop a flow

**Comment by Dr-N0** [comment]
@devinmatte Yeah, that would work for sure, I'll send something back in a sec

**Comment by Dr-N0** [comment]
![unknown](https://user-images.githubusercontent.com/15280703/106310133-20508700-6231-11eb-8fad-b1d911ae1ac6.png)

**Comment by Dr-N0** [comment]
Is something like this what you were thinking of? @devinmatte
