### ISSUE TITLE
Add Employers to Alumni Page

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/CSHPublicSite#33]
Interesting ones I know of:
Intuit,
Patreon,
Expensify,
Palantir,
LastPass
Exablox.
There are probably more, but those are missing for sure.

**Comment by brandonhudson** [comment]
Added additional alumni cards for:
- Intuit
- Dropbox
- Exablox

I have held off on the others for now, as I want to verify that we do indeed have full time employees at these companies before listing them. If you know the alum that work at these companies, include them here and i'll add them. 

This update will be included when my latest pull request is merged into master and deployed. See https://github.com/ComputerScienceHouse/CSHPublicSite/pull/50 for reference.

**Comment by gambogi** [comment]
Patreon: Henry Brown, but he works at Time now
Expensify: Eli Wenig
Palantir: Chris Lockfort
LastPass: Anatoly Ivasyuk

**Comment by gambogi** [comment]
Not sure about overlap with the current list, but we also have members at:
Über: Shella Stephens
Oculus: Hammerstien, Howland
Harvard: Rory
Thimble: David Brenner

**Comment by brandonhudson** [comment]
I will add Uber, Oculus, and Harvard when I get back to floor. I want to hold off on Thimble for the meantime until their campaign finishes on Kickstarter and everything is officially a green light - thats about a month out.

**Comment by brandonhudson** [comment]
Resolved in Pending PR https://github.com/ComputerScienceHouse/CSHPublicSite/pull/59 as of 01/18/16.

**Comment by gambogi** [comment]
Does that include Time, Expensify, Palantir, and lastpass?

**Comment by brandonhudson** [comment]
Time as in magazine, correct?

**Comment by gambogi** [comment]
Yeah

**Comment by brandonhudson** [comment]
Okay, ill add them momentarily.

**Comment by gambogi** [comment]
sweet

**Comment by brandonhudson** [comment]
Added to PR https://github.com/ComputerScienceHouse/CSHPublicSite/pull/59
