### ISSUE TITLE
Create Twitter Card for CSH links on Twitter

### ISSUE THREAD

**Issue by rswiernik** [ComputerScienceHouse/CSHPublicSite#37]

**Comment by rswiernik** [comment]
https://dev.twitter.com/cards/types/summary

**Comment by brandonhudson** [comment]
Added twitter card with CSH logo to all pages in https://github.com/ComputerScienceHouse/CSHPublicSite/pull/50. 

TODO:
- Update image to new purple/white card for both Facebook and Twitter

![screen shot 2015-12-12 at 2 18 45 am](https://cloud.githubusercontent.com/assets/3893578/11760784/dbe35c04-a076-11e5-9576-c7afaea3e60d.png)

**Comment by brandonhudson** [comment]
Verified to be added to 2016 Site Rewrite as of 01/18/16
