### ISSUE TITLE
Donation Page

### ISSUE THREAD

**Issue by AndrewHanes** [ComputerScienceHouse/CSHPublicSite#43]
Add a page about how to donate to floor

**Comment by brandonhudson** [comment]
Working to get relevant and accurate content for this as of 01/18/16.

**Comment by rswiernik** [comment]
Removing this from the 2016-site-rewrite as it is not critical to release and this information is taking a while to gather.

**Comment by rswiernik** [comment]
This is partially fixed with the 40th registration, however a more permanent link should be included somewhere.

**Comment by stevenmirabito** [comment]
We should reach out to Alumni Relations and see if there's a way for them to set up a permanent donation portal.

**Comment by stevenmirabito** [comment]
Actually, while the experience is terrible, it looks like if you go to the generic "Give to RIT" page it will allow you to choose Computer Science House as the sole beneficiary:

https://www.rit.edu/giving/makeagift

![](http://i.imgur.com/P62U2IE.png)

**Comment by mbillow** [comment]
I think we should have an entire page dedicated to alumni getting involved. That way we can include account recovery information as well as donation info.

**Comment by RamZallan** [comment]
We now have a direct link to donate through RIT's system, closing.
