### ISSUE TITLE
Why is this a fork?

### ISSUE THREAD

**Issue by sman591** [ComputerScienceHouse/CSHPublicSite#52]
This is Computer Science House's public website - and is over 100 commits ahead of it's current fork. I don't think this is any one member's project anymore, nor should it be as it is literally house's website: maintained and contributed to by a variety of members throughout anyone's time here.

Not sure if GitHub support is able to just toggle a flag on the repo to make it an organization-owned repo instead of a fork (I think I emailed GitHub support a few years ago and they were able to do this, but I could easily be wrong) or we'd have to delete & re-create the repo, but either way I feel it is worthwhile.

**Comment by worr** [comment]
Keep in mind that if you care about PR discussion history, you'll lose that if you delete and recreate.

**Comment by sman591** [comment]
@worr Yeah, that's the biggest downside to the delete and recreate I can think of. But if it comes down to that, I feel like it's better now then years from now.

**Comment by rswiernik** [comment]
There are a couple other critical repos that are also forks. I had brought this up early in the year, I haven't talked to anybody about it in a while, however I might be moving forward with that over break at some point. I'm gonna close this issue, as it's not only this repo, but know that it will likely happen.
