### ISSUE TITLE
Header placement issue

### ISSUE THREAD

**Issue by rswiernik** [ComputerScienceHouse/CSHPublicSite#58]
If you look at the header between the membership and the contact page, you can see that they differ in horizontal placement by like 5 pixels or so.

**Comment by brandonhudson** [comment]
Can you upload a screenshot? I don't know what you mean.

**Comment by rswiernik** [comment]
You can see it in this shot, the logo in the upper left is misaligned by like 10 pixels but only for some of the pages. Windows are the same width.

![website_header_misalignment](https://cloud.githubusercontent.com/assets/3595768/12407908/83eae672-be29-11e5-894d-7ed39c5bd447.PNG)

**Comment by brandonhudson** [comment]
Is that the membership page on the top? or the homepage? My main reason is that there may be another bug unrelated to this that ill open an issue for.

**Comment by rswiernik** [comment]
The top one is the main page, the bottom is the contact page.

**Comment by brandonhudson** [comment]
okay

**Comment by brandonhudson** [comment]
![screen shot 2016-01-18 at 9 40 57 pm 2](https://cloud.githubusercontent.com/assets/3893578/12408226/6c2e210e-be2c-11e5-9421-20b2515529a7.png)
I can't seem to replicate that on either Chrome or Safari. Ill double check on Firefox with the css visualizer to split the two into layers, but the classes applied to that image are not page dependent and there is nothing added to the contacts page that should cause that...

**Comment by brandonhudson** [comment]
Caused by having a scroll bar on Members and not on contact. Nothing we can do about that really unless we implement our own scroll bar - which I personally think is a little overkill for this.

**Comment by rswiernik** [comment]
HA. My bad. Didn't even think of that!
