### ISSUE TITLE
Home Link Bug

### ISSUE THREAD

**Issue by brandonhudson** [ComputerScienceHouse/CSHPublicSite#60]
Add active class to Home link when visiting wwwtest.csh.rit.edu/

Currently only working with wwwtest.csh.rit.edu/index.html

**Comment by rswiernik** [comment]
:+1:

**Comment by brandonhudson** [comment]
Resolved in Pending PR https://github.com/ComputerScienceHouse/CSHPublicSite/pull/59 as of 01/18/16.
