### ISSUE TITLE
Navbar shrink animation is extremely jarring

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/CSHPublicSite#64]
As @mbillow and some others have mentioned over the course of this project, the animation when the navbar shrinks on scroll is too jarring and should be smooth like this example: http://callmenick.com/_development/resize-header-on-scroll/

May not be fixable, but worth looking into in my opinion.

**Comment by rswiernik** [comment]
This refers to code in the 2016-site-rewrite branch.

**Comment by brandonhudson** [comment]
Main trouble here is two things:
1) the 'brand' is an image, which scales differently than text (like your example)
2) we are modifying the size of the text for each navigation item, which is why it does the pull-back animation into a corner.

**Comment by brandonhudson** [comment]
Resolved (to remove clipping of logo) in Pending PR: https://github.com/ComputerScienceHouse/CSHPublicSite/pull/59
