### ISSUE TITLE
Pictures in the tour are outdated and don't reflect the current state of floor

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/CSHPublicSite#66]
At some point when the semester gets going again, we should take some new pictures for the tour page. @rossdylan also has a cool photosphere of the server room that can be embedded on the page.

**Comment by rswiernik** [comment]
Floor needs to be in a more reasonable state, but I would like those to be updated.

**Comment by rswiernik** [comment]
Server room photosphere add in PR #80.
