### ISSUE TITLE
Contact form validation doesn't check the position select box

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/CSHPublicSite#67]
Upon attempting to submit an empty contact form, the validation should fail the select box when a valid position is not selected:

![](http://i.imgur.com/OSoRGEO.png)

**Comment by rswiernik** [comment]
This is intentional. There are times where you want to email the organization not a specific person.

**Comment by brandonhudson** [comment]
The submission is handled with a default case in mailer.php to send to chairman if position is null.
