### ISSUE TITLE
Possible to have duplicate sponsors appear on the homepage

### ISSUE THREAD

**Issue by stevenmirabito** [ComputerScienceHouse/CSHPublicSite#68]
While rare, it's possible to randomly select 4 sponsors and get duplicates, resulting in a sponsor showing up 2 or more times on the homepage. Each sponsor selected should be removed from the array before selecting the next one.

![](http://i.imgur.com/IzKkFSp.png)

**Comment by brandonhudson** [comment]
Resolved in pending PR https://github.com/ComputerScienceHouse/CSHPublicSite/pull/59
