### ISSUE TITLE
Page titles aren't page-specific

### ISSUE THREAD

**Issue by sman591** [ComputerScienceHouse/CSHPublicSite#99]
All of the page titles are "Computer Science House". This makes using one's browser history for our website useless:
![screenshot 2016-02-12 15 26 53](https://cloud.githubusercontent.com/assets/1441807/13019392/29bda90a-d19d-11e5-9c59-18b545b80080.png)

And our results on Google would be pretty bland. These are some current pages - imagine what this would be like if they were all "Computer Science House"....
![screenshot 2016-02-12 15 29 10](https://cloud.githubusercontent.com/assets/1441807/13019460/9eae3ec8-d19d-11e5-8abd-0efad977701c.png)

**Comment by brandonhudson** [comment]
Fixed in https://github.com/ComputerScienceHouse/CSHPublicSite/pull/104

**Comment by rswiernik** [comment]
Merged and pushed.
